/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import Servicios.UserServicios;
import java.awt.Cursor;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.ProcesosDB;

/**
 *
 * @author SSM01
 */
public class Login extends javax.swing.JFrame {

    //para conectar a la DB
    //ProcesosDB Modelo = new ProcesosDB();
    //PreparedStatement pstmt =   null;
    int mouseX, mouseY;
    public Cursor cursor; //variable cursor
    public Login() {
        setUndecorated(true); //ocultar la barra de titulo
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginCard = new javax.swing.JPanel();
        bienvenido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        userLbl = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Passwordlbl = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        loginBttn = new javax.swing.JLabel();
        errorLoginlbl = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        titlePanel = new javax.swing.JPanel();
        minimizebttn = new javax.swing.JLabel();
        closebttn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(300, 420));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginCard.setBackground(new java.awt.Color(255, 255, 255));
        loginCard.setPreferredSize(new java.awt.Dimension(300, 400));
        loginCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginCardMouseEntered(evt);
            }
        });
        loginCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bienvenido.setForeground(new java.awt.Color(0, 0, 0));
        bienvenido.setText("Bienvenido");
        loginCard.add(bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 65, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(159, 34, 65));
        jSeparator1.setForeground(new java.awt.Color(159, 34, 65));
        loginCard.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 76, 86, 10));

        jSeparator2.setBackground(new java.awt.Color(159, 34, 65));
        jSeparator2.setForeground(new java.awt.Color(159, 34, 65));
        loginCard.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, 62, 10));

        userLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userLbl.setText("Usuario:");
        loginCard.add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 115, -1, -1));

        userField.setBackground(new java.awt.Color(255, 255, 255));
        userField.setBorder(null);
        loginCard.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 141, 253, -1));
        loginCard.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 163, 253, 10));

        Passwordlbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Passwordlbl.setText("Contraseña:");
        loginCard.add(Passwordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 187, -1, -1));

        passwordField.setBackground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(null);
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        loginCard.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 213, 253, -1));
        loginCard.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 235, 253, 10));

        loginBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/login.png"))); // NOI18N
        loginBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBttnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBttnMouseExited(evt);
            }
        });
        loginCard.add(loginBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 287, -1, -1));

        errorLoginlbl.setForeground(new java.awt.Color(255, 0, 0));
        loginCard.add(errorLoginlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 251, -1, -1));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/logo_edomex.png"))); // NOI18N
        loginCard.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/logo_rlh.png"))); // NOI18N
        loginCard.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        getContentPane().add(loginCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));
        titlePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titlePanelMouseDragged(evt);
            }
        });
        titlePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlePanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titlePanelMousePressed(evt);
            }
        });
        titlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizebttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/minimize.png"))); // NOI18N
        minimizebttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizebttnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizebttnMouseEntered(evt);
            }
        });
        titlePanel.add(minimizebttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        closebttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/close.png"))); // NOI18N
        closebttn.setToolTipText("");
        closebttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebttn(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closebttnMouseEntered(evt);
            }
        });
        titlePanel.add(closebttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        getContentPane().add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closebttn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebttn
       dispose();
    }//GEN-LAST:event_closebttn

    private void closebttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebttnMouseEntered
        closebttn.setCursor(new Cursor(cursor.HAND_CURSOR)); //pasa el cursor de la flechita a la mano
    }//GEN-LAST:event_closebttnMouseEntered

    private void minimizebttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebttnMouseClicked
       //minimizar la ventana
       setState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizebttnMouseClicked

    private void minimizebttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizebttnMouseEntered
        minimizebttn.setCursor(new Cursor(cursor.HAND_CURSOR)); //pasa el cursor de la flechita a la mano
    }//GEN-LAST:event_minimizebttnMouseEntered

    private void titlePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMouseClicked

    }//GEN-LAST:event_titlePanelMouseClicked

    private void titlePanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMouseDragged

        // Obtener la posición actual de la ventana y moverla según la posición del mouse
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_titlePanelMouseDragged

    private void loginCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginCardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_loginCardMouseEntered

    private void loginBttnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBttnMouseEntered
       loginBttn.setCursor(new Cursor(cursor.HAND_CURSOR));
       loginBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/login_hover.png")));
       loginBttn.setLocation(loginBttn.getX()-2, loginBttn.getY()-2);
    }//GEN-LAST:event_loginBttnMouseEntered

    private void loginBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBttnMouseClicked
       UserServicios usuarioServicio = new UserServicios();
        String user = userField.getText();
       String password = passwordField.getText();
       
       boolean exito = usuarioServicio.iniciarSesion(user, password);
        
       if(exito == true){
           usuarioServicio.buscarUsuario(user);
           this.dispose();
           vMain vMain = new vMain();
           vMain.setVisible(true);
       }else{
           if(user.isEmpty() || password.isEmpty()){
           errorLoginlbl.setText("Los campos no pueden estar vacios");
            }else{
                errorLoginlbl.setText("Usuario y/o contraseña incorrectos" );
            }
       }
    }//GEN-LAST:event_loginBttnMouseClicked

    private void loginBttnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBttnMouseExited
        loginBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon/login.png")));
         loginBttn.setLocation(loginBttn.getX()+2, loginBttn.getY()+2);
    }//GEN-LAST:event_loginBttnMouseExited

    private void titlePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlePanelMousePressed

        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_titlePanelMousePressed
//handler para que cuando se presione enter en la password se ejecute la accion del boton
    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
            //no se puede usar el metodo doClick para simular la presion del boton, ya que el elemento loginBttn no es en si un boton si no una lbl
        UserServicios usuarioServicio = new UserServicios();
       String user = userField.getText();
       String password = passwordField.getText();
       boolean exito = usuarioServicio.iniciarSesion(user, password);
        
       if(exito){
           usuarioServicio.buscarUsuario(user);
           this.dispose();
           vMain vMain = new vMain();
           vMain.setVisible(true);
       }else{
           if(user.isEmpty() || password.isEmpty()){
           errorLoginlbl.setText("Los campos no pueden estar vacios");
            }else{
                errorLoginlbl.setText("Usuario y/o contraseña incorrectos" );
            }
       }       
    }//GEN-LAST:event_passwordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Passwordlbl;
    private javax.swing.JLabel bienvenido;
    private javax.swing.JLabel closebttn;
    private javax.swing.JLabel errorLoginlbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel loginBttn;
    private javax.swing.JPanel loginCard;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel minimizebttn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLbl;
    // End of variables declaration//GEN-END:variables
}
